name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['18.x', '20.x', '22.x', '23.x']
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build
        run: make

  build-deno:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deno-version: [v2.x]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Set up Deno ${{ matrix.deno-version }}
        uses: denolib/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno-version }}
      - name: Build
        run: make -f deno.mk
