name: Pipeline

on:
  push:

jobs:
  build-deno:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deno-version: [v2.x]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Set up Deno ${{ matrix.deno-version }}
        uses: denolib/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno-version }}
      - name: Build
        run: make
      - name: Upload docs
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/@muspellheim/shared/0.3.0/ # TODO extract version as variable

  build-node:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['18.x', '20.x', '22.x', '23.x']
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build
        run: make -f node.mk

  deploy-docs:
    runs-on: ubuntu-latest
    needs: build-deno
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
